### ISSUE TITLE
Add BPS information

### ISSUE THREAD

**Issue by ruslaniv** [purpl3F0x/MQA_identifier#11]
Would it be possible to add BPS information in the app output?

**Comment by purpl3F0x** [comment]
Bits per second?
That's irrelevant. (And also constant 44.1/48 * 24bits)

**Comment by ruslaniv** [comment]
Oh, you mean 24 bits is implied? 
In other words, if it was 16 bits it would not have been MQA?

**Comment by purpl3F0x** [comment]
You can. If the master is 16bit and not greater than 48Khz the output is 16bit. or it's specially made for MQA-CD to be 44.1/16.
But that's easily obtainable, maybe i added in the future
